name: lrk_health_water
description: Life Records Keeper water consumption application
version: 0.0.1
homepage: https://github.com/pescuma/lrk

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
#  path: ^1.8.0

  lrk_common:
    path: ../common

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  fake_async: ^1.2.0

  lrk_common_testing:
    path: ../common_testing
