name: lrk_common_testing
description: Life Records Keeper commons testing package
version: 0.0.1
homepage: https://github.com/pescuma/lrk

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  dart_date: ^1.1.0
  fake_async: ^1.2.0

  lrk_common:
    path: ../common

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
