name: lrk_gui_cli
description: Life Records Keeper CLI
version: 0.0.1
homepage: https://github.com/pescuma/lrk

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  args: ^2.3.0
  klizma: ^0.2.0
  interact: ^2.1.1
  quiver: ^3.0.1

  lrk_common:
    path: ../common

  lrk_health_water:
    path: ../health_water

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
