name: lrk_gui_cli
description: Life Records Keeper CLI
version: 0.0.1
homepage: https://github.com/pescuma/lrk

environment:
  sdk: '>=2.14.3 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
