name: lrk_gui_cli
description: Life Records Keeper CLI
version: 0.0.1
homepage: https://github.com/pescuma/lrk

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  platform: ^3.0.2
  dart_app_data: ^1.0.1
  args: ^2.3.0
  interact: ^2.1.1
  intl: ^0.17.0
  tabular: ^0.6.3

  lrk_gui_common:
    path: ../gui_common

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
