name: lrk_common
description: Life Records Keeper commons package
version: 0.0.1
homepage: https://github.com/pescuma/lrk

publish_to: 'none'

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  dart_date: ^1.1.0
  darq: ^1.1.1
  lazy_memo: ^0.1.2
  clock: ^1.1.0
  cron: ^0.4.0
  quiver: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
