name: lrk_db_sqlite
description: Life Records Keeper sqlite db
version: 0.0.1
homepage: https://github.com/pescuma/lrk

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  drift: ^1.0.1
  sqlite3: ^1.2.0
  path_provider: ^2.0.0
  path: ^1.8.0

  lrk_common:
    path: ../common

  lrk_health_water:
    path: ../health_water

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  drift_dev: ^1.0.2
  build_runner: ^2.1.4


